trigger:
  batch: true
  branches:
    include:
    - main
    - feature/*
    - bugfix/*

pr:
  branches:
    include:
    - main
    
variables:
- template: templates/variables/release.yml
  
stages:
- stage: Build
  displayName: Build
  variables:
  - group: Build
  jobs:
  - template: templates/jobs/build.yml
      
- stage: PreProd
  displayName: PreProd
  dependsOn: Build
  condition: succeeded()
  variables: 
  - template: templates/variables/preprod.yml
  - group: PreProd
  jobs:
  - template: templates/jobs/deploy.yml
    parameters: 
      environment: PreProd
      azureServiceConnection: $(azureServiceConnection)
      azureSubscription: $(azureSubscription)
      resourceGroupName: $(resourceGroupName)
      location: $(location)
      discordBotSettings:
        DailyScheduleTimerTrigger: $(dailyScheduleTimerTrigger)
        DiscordApiUrl: $(discordApiUrl)
        DiscordBotApplicationId: $(discordBotApplicationId)
        DiscordEventsUrl: $(discordEventsUrl)
        DiscordGuildId: $(discordGuildId)
        DiscordNotificationGroupIds: $(discordNotificationGroupIds)
        DiscordScheduleChannelId: $(discordScheduleChannelId)
        DiscordStreamGoLiveChannelId: $(discordStreamGoLiveChannelId)
        DiscordVideoChannelId: $(discordVideoChannelId)
      orchestratorSettings:
        EventScheduleTimerTrigger: $(eventScheduleTimerTrigger)
        TwitchApiChannelEndpoint: $(twitchApiChannelEndpoint)
        TwitchApiClipEndpoint: $(twitchApiClipEndpoint)
        TwitchApiGameEndpoint: $(twitchApiGameEndpoint)
        TwitchApiScheduleEndpoint: $(twitchApiScheduleEndpoint)
        TwitchApiUrl: $(twitchApiUrl)
        TwitchApiVideoEndpoint: $(twitchApiVideoEndpoint)
        TwitchBaseUrl: $(twitchBaseUrl)
        TwitchBroadcasterId: $(twitchBroadcasterId)
        TwitchClientId: $(twitchClientId)
        TwitchClipsTimerTrigger: $(twitchClipsTimerTrigger)
        TwitchHighlightsTimerTrigger: $(twitchHighlightsTimerTrigger)
        TwitchStreamChangeTopic: $(twitchStreamChangeTopic)
        TwitchSubscriptionUrl: $(twitchSubscriptionUrl)
        TwitchTokenUrl: $(twitchTokenUrl)
        YoutubeChannelId: $(youtubeChannelId)
        YoutubeSubscriptionUrl: $(youtubeSubscriptionUrl)
        YoutubeVideoTopic: $(youtubeVideoTopic)
        YoutubeVideoUrl: $(youtubeVideoUrl)
      discordBotSecrets:
        DiscordBotToken: $(DiscordBotToken)
      orchestratorSecrets:
        TwitchClientSecret: $(TwitchApiClientSecret)
        YoutubeApiKey: $(YoutubeApiKey)

- stage: Production
  displayName: Production
  dependsOn: PreProd
  condition:  and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables: 
  - template: templates/variables/production.yml
  - group: Production
  jobs:
  - template: templates/jobs/deploy.yml
    parameters: 
      environment: Production
      azureServiceConnection: $(azureServiceConnection)
      azureSubscription: $(azureSubscription)
      resourceGroupName: $(resourceGroupName)
      location: $(location)
      discordBotSettings:
        DailyScheduleTimerTrigger: $(dailyScheduleTimerTrigger)
        DiscordApiUrl: $(discordApiUrl)
        DiscordBotApplicationId: $(discordBotApplicationId)
        DiscordEventsUrl: $(discordEventsUrl)
        DiscordGuildId: $(discordGuildId)
        DiscordNotificationGroupIds: $(discordNotificationGroupIds)
        DiscordScheduleChannelId: $(discordScheduleChannelId)
        DiscordStreamGoLiveChannelId: $(discordStreamGoLiveChannelId)
        DiscordVideoChannelId: $(discordVideoChannelId)
      orchestratorSettings:
        EventScheduleTimerTrigger: $(eventScheduleTimerTrigger)
        TwitchApiChannelEndpoint: $(twitchApiChannelEndpoint)
        TwitchApiClipEndpoint: $(twitchApiClipEndpoint)
        TwitchApiGameEndpoint: $(twitchApiGameEndpoint)
        TwitchApiScheduleEndpoint: $(twitchApiScheduleEndpoint)
        TwitchApiUrl: $(twitchApiUrl)
        TwitchApiVideoEndpoint: $(twitchApiVideoEndpoint)
        TwitchBaseUrl: $(twitchBaseUrl)
        TwitchBroadcasterId: $(twitchBroadcasterId)
        TwitchClientId: $(twitchClientId)
        TwitchClipsTimerTrigger: $(twitchClipsTimerTrigger)
        TwitchHighlightsTimerTrigger: $(twitchHighlightsTimerTrigger)
        TwitchStreamChangeTopic: $(twitchStreamChangeTopic)
        TwitchSubscriptionUrl: $(twitchSubscriptionUrl)
        TwitchTokenUrl: $(twitchTokenUrl)
        YoutubeChannelId: $(youtubeChannelId)
        YoutubeSubscriptionUrl: $(youtubeSubscriptionUrl)
        YoutubeVideoTopic: $(youtubeVideoTopic)
        YoutubeVideoUrl: $(youtubeVideoUrl)
      discordBotSecrets:
        DiscordBotToken: $(DiscordBotToken)
      orchestratorSecrets:
        TwitchClientSecret: $(TwitchApiClientSecret)
        YoutubeApiKey: $(YoutubeApiKey)
