trigger:
  branches:
    include:
    - main
    - feature/*
    - bugfix/*

pr:
  branches:
    include:
    - main
    
variables:
  vmImageName: 'windows-2022'
  azureSubscription: '0e43496e-dd9f-4359-8a9d-227bc76d5e01'
  
stages:
- stage: Build
  displayName: Build
  jobs:
  - template: templates/jobs/build.yml
    parameters: 
      vmImageName: $(vmImageName)
      
- stage: PreProd
  displayName: PreProd
  dependsOn: Build
  condition: succeeded()
  variables: 
  - template: templates/variables/preprod.yml
  - group: PreProd
  jobs:
  - template: templates/jobs/deploy.yml
    parameters: 
      vmImageName: $(vmImageName)
      environment: $(environmemt)
      azureSubscription: $(azureSubscription)
      resourceGroupName: $(resourceGroupName)

- stage: Production
  displayName: Production
  dependsOn: Staging
  condition:  and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables: 
  - template: templates/variables/production.yml
  - group: Production
  jobs:
  - template: templates/jobs/deploy.yml
    parameters: 
      vmImageName: $(vmImageName)
      environment: $(environmemt)
      azureSubscription: $(azureSubscription)
      resourceGroupName: $(resourceGroupName)
