parameters:
- name: vmImageName
  type: string
  default: 'windows-2022'

jobs:
- job: Build
  displayName: Build
  pool:
    vmImage: ${{ parameters.vmImageName }}

  steps:
  - task: DotNetCoreCLI@2
    displayName: Run unit tests
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/*.csproj'
      arguments: '-o $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
      modifyOutputPath: true

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: drop