parameters:
- name: vmImageName
  type: string
  default: 'windows-2022'

jobs:
- job: Build
  displayName: Build
  pool:
    vmImage: ${{ parameters.vmImageName }}

  steps:
  - task: PublishPipelineArtifact@1
    displayName: 'Publish bicep file'
    inputs:
      targetPath: '$(Build.SourcesDirectory)/Deployment/Resources/resourceGroup.bicep'
      artifactType: 'pipeline'
      artifactName: 'infrastructure'
      
  - task: DotNetCoreCLI@2
    displayName: 'Install dotnet-stryker'
    inputs:
      command: custom
      custom: tool
      arguments: install dotnet-stryker --tool-path $(Agent.BuildDirectory)/tools

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'raw13'
      scannerMode: 'MSBuild'
      projectKey: 'RAW1303_StreamingNotificationFunctionApp'

  - task: DotNetCoreCLI@2
    displayName: Run unit tests
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      publishTestResults: true
      arguments: '--no-restore --collect "Code Coverage"'

  - task: SonarCloudAnalyze@1

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/*.csproj'
      arguments: '-o $(Build.ArtifactStagingDirectory) --no-restore'
      zipAfterPublish: true
      modifyOutputPath: true
      
  - task: PublishPipelineArtifact@1
    displayName: Publish Code
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactType: 'pipeline'
      artifactName: 'code'
      
  - task: Powershell@2
    displayName: 'Run dotnet-stryker'
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)/Raw.Streaming.Discord.Tests'
      targetType: 'inline'
      pwsh: true
      script: '$(Agent.BuildDirectory)/tools/dotnet-stryker --dashboard-api-key $(StrykerApiKey) -v $(Build.SourceBranch)'
      
  - task: Powershell@2
    displayName: 'Run dotnet-stryker'
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)/Raw.Streaming.Webhook.Tests'
      targetType: 'inline'
      pwsh: true
      script: '$(Agent.BuildDirectory)/tools/dotnet-stryker --dashboard-api-key $(StrykerApiKey) -v $(Build.SourceBranch)'
      
  - task: PublishMutationReport@1
    displayName: 'Publish Raw.Streaming.Discord.Tests Mutation Test Report'
    inputs:
      reportPattern: '$(Build.SourcesDirectory)/Raw.Streaming.Discord.Tests/**/mutation-report.html'
      reportDisplayName: 'Raw.Streaming.Discord.Tests'
      
  - task: PublishMutationReport@1
    displayName: 'Publish Raw.Streaming.Webhook.Tests Mutation Test Report'
    inputs:
      reportPattern: '$(Build.SourcesDirectory)/Raw.Streaming.Webhook.Tests/**/mutation-report.html
      reportDisplayName: 'Raw.Streaming.Webhook.Tests'

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
