parameters:
- name: environment
  type: string
- name: azureSubscription
  type: string
- name: resourceGroupName
  type: string
- name: vmImageName
  type: string
  default: 'windows-2022'
- name: discordBotFunctionAppSuffix
  type: string
  default: 'DiscordBot'
- name: orchestrationAppSuffix
  type: string
  default: 'Orchestration'

jobs:
- deployment: Deploy
  displayName: Deploy
  environment: $(environment)
  pool:
    vmImage: $(vmImageName)

  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureFunctionApp@1
          displayName: 'Deploy Discord Bot'
          inputs:
            azureSubscription: '$(azureSubscription)'
            appType: functionApp
            appName: '$(resourceGroupName)$(discordBotFunctionAppSuffix)'
            package: '$(Pipeline.Workspace)/drop/Raw.Streaming.Discord.zip'
            resourceGroupName: $(resourceGroupName)

        - task: AzureFunctionApp@1
          displayName: 'Deploy Orchestrator'
          inputs:
            azureSubscription: '$(azureSubscription)'
            appType: functionApp
            appName: '$(resourceGroupName)$(orchestrationAppSuffix)'
            package: '$(Pipeline.Workspace)/drop/Raw.Streaming.Webhook.zip'
            resourceGroupName: $(resourceGroupName)