parameters:
- name: environment
  type: string
- name: azureSubscription
  type: string
- name: resourceGroupName
  type: string
- name: vmImageName
  type: string
  default: 'windows-2022'
- name: discordBotFunctionAppSuffix
  type: string
  default: 'DiscordBotFA'
- name: orchestrationAppSuffix
  type: string
  default: 'OrchestrationFA'

jobs:
- deployment: Deploy
  displayName: Deploy
  environment: ${{ parameters.environment }}
  pool:
    vmImage: ${{ parameters.vmImageName }}

  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureFunctionApp@1
          displayName: 'Deploy Discord Bot'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            appType: functionApp
            appName: '${{ parameters.resourceGroupName }}${{ parameters.discordBotFunctionAppSuffix }}'
            package: '$(Pipeline.Workspace)/drop/Raw.Streaming.Discord.zip'
            resourceGroupName: ${{ parameters.resourceGroupName }}

        - task: AzureFunctionApp@1
          displayName: 'Deploy Orchestrator'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            appType: functionApp
            appName: '${{ parameters.resourceGroupName }}${{ parameters.orchestrationAppSuffix }}'
            package: '$(Pipeline.Workspace)/drop/Raw.Streaming.Discord.zip'
            resourceGroupName: ${{ parameters.resourceGroupName }}